### PR TITLE
Forgot to export the reset function

### PR DESCRIPTION
**Pull request by gazpachu**

### CODE REVIEW

**Comment by nathpaiva** [comment]
@rohitdatta Is it possible to merge this? It would be awesome to use it on my project.

**Comment by nathpaiva** [comment]
@colevscode and @vitormorales 

This PR exposes the `reset` function so that way we can control the form after submission, it would be awesome to have it on this library.

**Comment by rohitdatta** [comment]
@gazpachu @nathpaiva sorry I didn't get an email when this PR was first opened, but we published on a new version 2.2.4

**Comment by nathpaiva** [comment]
@rohitdatta no worries, thank you very much to merge it! 
It'll help me a lot! 🎊

**Pull request merged**
